sudo: required

language: python

python:
  - "3.6"

env:
  - CONTAINER_IMAGE_NAME=quay.io/cosee-concourse/serverless-resource

services:
  - docker

script:
  - pytest
  - ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$QUAY_USER" -p="$QUAY_APIKEY" quay.io;
      docker push $CONTAINER_IMAGE_NAME;
    fi