resources:
- name: aws-production
  type: serverless
  source:
    apiKey: apiKey123
    secretKey: secretKey123

resource_types:
- name: serverless
  type: docker-image
  source:
    repository: quay.io/cosee-concourse/serverless-resource

jobs:
- name: deploy
  serial: true
  plan:
  - put: aws-production
    params:
      - stage: production
      - deploy: true
      - directory: artifact
